"""Initial

Revision ID: bf30fd8580ee
Revises: 
Create Date: 2021-12-02 14:24:03.891254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf30fd8580ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=511), nullable=True),
    sa.Column('surname', sa.String(length=511), nullable=True),
    sa.Column('patronymic', sa.String(length=511), nullable=True),
    sa.Column('email', sa.String(length=511), nullable=True),
    sa.Column('password', sa.String(length=511), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_name', 'users', ['name'], unique=False, postgresql_ops={'name': 'varchar_pattern_ops'})
    op.create_index('ix_users_patronymic', 'users', ['patronymic'], unique=False, postgresql_ops={'patronymic': 'varchar_pattern_ops'})
    op.create_index('ix_users_surname', 'users', ['surname'], unique=False, postgresql_ops={'surname': 'varchar_pattern_ops'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_surname', table_name='users', postgresql_ops={'surname': 'varchar_pattern_ops'})
    op.drop_index('ix_users_patronymic', table_name='users', postgresql_ops={'patronymic': 'varchar_pattern_ops'})
    op.drop_index('ix_users_name', table_name='users', postgresql_ops={'name': 'varchar_pattern_ops'})
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
